#pragma once

constexpr auto KBDKEY_POVT = 1;     // ПОВТ
constexpr auto KBDKEY_KT = 2;       // КТ
constexpr auto KBDKEY_DELRIGHT = 3; // del rgt
constexpr auto KBDKEY_SDV = 4;      // del
constexpr auto KBDKEY_RAZDV = 5;    // ins
constexpr auto KBDKEY_INDSU = 6;    // ИНДСУ
constexpr auto KBDKEY_BLKRED = 7;   // БЛОКРЕД
constexpr auto KBDKEY_SHAG = 8;     // ШАГ
constexpr auto KBDKEY_SBR = 9;      // СБР
constexpr auto KBDKEY_STOP = 10;    // СТОП
constexpr auto KBDKEY_DSHIFT = 11;  // shift
constexpr auto KBDKEY_SEMI = 12;    // ;
constexpr auto KBDKEY_1 = 13;       // 1
constexpr auto KBDKEY_2 = 14;       // 2
constexpr auto KBDKEY_3 = 15;       // 3
constexpr auto KBDKEY_4 = 16;       // 4
constexpr auto KBDKEY_5 = 17;       // 5
constexpr auto KBDKEY_6 = 18;       // 6
constexpr auto KBDKEY_7 = 19;       // 7
constexpr auto KBDKEY_8 = 20;       // 8
constexpr auto KBDKEY_9 = 21;       // 9
constexpr auto KBDKEY_0 = 22;       // 0
constexpr auto KBDKEY_MINUS = 23;   // -
constexpr auto KBDKEY_COLON = 24;   // :
constexpr auto KBDKEY_BACKSPACE =  25;  // backspace
constexpr auto KBDKEY_TAB = 26;     // ТАБ
constexpr auto KBDKEY_J = 27;       // J
constexpr auto KBDKEY_C = 28;       // C
constexpr auto KBDKEY_U = 29;       // U
constexpr auto KBDKEY_K = 30;       // K
constexpr auto KBDKEY_E = 31;       // E
constexpr auto KBDKEY_N = 32;       // N
constexpr auto KBDKEY_G = 33;       // G
constexpr auto KBDKEY_LEFTBR = 34;  // [
constexpr auto KBDKEY_RIGHTBR = 35; // ]
constexpr auto KBDKEY_Z = 36;       // Z
constexpr auto KBDKEY_H = 37;       // H
constexpr auto KBDKEY_RIFHTFBR = 38;  // Ъ
constexpr auto KBDKEY_QUESTION = 39;  // /
constexpr auto KBDKEY_BC = 40;      // ВС
constexpr auto KBDKEY_SU = 41;      // СУ
constexpr auto KBDKEY_F = 42;       // F
constexpr auto KBDKEY_Y = 43;       // Y
constexpr auto KBDKEY_W = 44;       // W
constexpr auto KBDKEY_A = 45;       // A
constexpr auto KBDKEY_P = 46;       // P
constexpr auto KBDKEY_R = 47;       // R
constexpr auto KBDKEY_O = 48;       // O
constexpr auto KBDKEY_L = 49;       // L
constexpr auto KBDKEY_D = 50;       // D
constexpr auto KBDKEY_V = 51;       // V
constexpr auto KBDKEY_BKSLASH = 52; // Э
constexpr auto KBDKEY_GREAT = 53;   // .
constexpr auto KBDKEY_ENTER = 54;   // enter
constexpr auto KBDKEY_ZAGL = 55;    // ЗАГЛ
constexpr auto KBDKEY_STR = 56;     // СТР
constexpr auto KBDKEY_Q = 57;       // Q
constexpr auto KBDKEY_CH = 58;      // Ч
constexpr auto KBDKEY_S = 59;       // S
constexpr auto KBDKEY_M = 60;       // M
constexpr auto KBDKEY_I = 61;       // I
constexpr auto KBDKEY_T = 62;       // T
constexpr auto KBDKEY_X = 63;       // X
constexpr auto KBDKEY_B = 64;       // B
constexpr auto KBDKEY_AT = 65;      // @
constexpr auto KBDKEY_LESS = 66;    // ,
constexpr auto KBDKEY_RUS = 67;     // РУС
constexpr auto KBDKEY_AR2 = 68;     // АР2
constexpr auto KBDKEY_SPACE = 69;   // space
constexpr auto KBDKEY_LAT = 70;     // ЛАТ
constexpr auto KBDKEY_LEFT = 71;    // left
constexpr auto KBDKEY_UP = 72;      // up
constexpr auto KBDKEY_DOWN = 73;    // down
constexpr auto KBDKEY_RIGHT = 74;   // right
//  PLEN
constexpr auto KBDKEY_GRAPH = 75;   // ГРАФ
constexpr auto KBDKEY_ZAP = 76;     // ЗАП
constexpr auto KBDKEY_STIR = 77;    // СТИР
constexpr auto KBDKEY_USTTAB = 78;  // УСТТАБ
constexpr auto KBDKEY_SBRTAB = 79;  // СБРТАБ
constexpr auto KBDKEY_GT = 80;      // ГТ
constexpr auto KBDKEY_LEFTUP = 81;  // left-up
constexpr auto KBDKEY_RIGHTUP = 82; // right-up
constexpr auto KBDKEY_TOP = 83;     // top
constexpr auto KBDKEY_LEFTDOWN = 84;  // left-down
constexpr auto KBDKEY_RIGHTDOWN = 85;  // right-down
constexpr auto KBDKEY_REZERV1 = 86; // Резерв
constexpr auto KBDKEY_REZERV2 = 87; // Резерв;
constexpr auto KBDKEY_REZERV3 = 88; // Резерв
constexpr auto KBDKEY_REZERV4 = 89; // Резерв;

constexpr auto SCANCODE_ESC = 9;
constexpr auto SCANCODE_F1 = 67;
constexpr auto SCANCODE_F2 = 68;
constexpr auto SCANCODE_F3 = 69;
constexpr auto SCANCODE_F4 = 70;
constexpr auto SCANCODE_F5 = 71;
constexpr auto SCANCODE_F6 = 72;
constexpr auto SCANCODE_F7 = 73;
constexpr auto SCANCODE_F8 = 74;
constexpr auto SCANCODE_F9 = 75;
constexpr auto SCANCODE_F10 = 76;
constexpr auto SCANCODE_F11 = 95;
constexpr auto SCANCODE_F12 = 96;
constexpr auto SCANCODE_SCRLLOCK = 78;
constexpr auto SCANCODE_BREAK = 127;

constexpr auto SCANCODE_TILDA = 49; // ~
constexpr auto SCANCODE_1 = 10;
constexpr auto SCANCODE_2 = 11;
constexpr auto SCANCODE_3 = 12;
constexpr auto SCANCODE_4 = 13;
constexpr auto SCANCODE_5 = 14;
constexpr auto SCANCODE_6 = 15;
constexpr auto SCANCODE_7 = 16;
constexpr auto SCANCODE_8 = 17;
constexpr auto SCANCODE_9 = 18;
constexpr auto SCANCODE_0 = 19;
constexpr auto SCANCODE_MINUS = 20;
constexpr auto SCANCODE_PLUS = 21;
constexpr auto SCANCODE_BACSPACE = 22;
constexpr auto SCANCODE_BACKSLASH = 51; // '\'

constexpr auto SCANCODE_TAB = 23;
constexpr auto SCANCODE_Q = 24;
constexpr auto SCANCODE_W = 25;
constexpr auto SCANCODE_E = 26;
constexpr auto SCANCODE_R = 27;
constexpr auto SCANCODE_T = 28;
constexpr auto SCANCODE_Y = 29;
constexpr auto SCANCODE_U = 30;
constexpr auto SCANCODE_I = 31;
constexpr auto SCANCODE_O = 32;
constexpr auto SCANCODE_P = 33;
constexpr auto SCANCODE_LEFTBR = 34; // [
constexpr auto SCANCODE_RIGHTBR = 35; // ]
constexpr auto SCANCODE_ENTER = 36;
constexpr auto SCANCODE_CAPS = 66; // Caps Lock
constexpr auto SCANCODE_A = 38;
constexpr auto SCANCODE_S = 39;
constexpr auto SCANCODE_D = 40;
constexpr auto SCANCODE_F = 41;
constexpr auto SCANCODE_G = 42;
constexpr auto SCANCODE_H = 43;
constexpr auto SCANCODE_J = 44;
constexpr auto SCANCODE_K = 45;
constexpr auto SCANCODE_L = 46;
constexpr auto SCANCODE_COLON = 47; // :
constexpr auto SCANCODE_QUOTE = 48; // "
constexpr auto SCANCODE_LSHIFT = 50; // Left Shift
constexpr auto SCANCODE_Z = 52;
constexpr auto SCANCODE_X = 53;
constexpr auto SCANCODE_C = 54;
constexpr auto SCANCODE_V = 55;
constexpr auto SCANCODE_B = 56;
constexpr auto SCANCODE_N = 57;
constexpr auto SCANCODE_M = 58;
constexpr auto SCANCODE_LESS = 59; // <
constexpr auto SCANCODE_GREAT = 60; // >
constexpr auto SCANCODE_QUESTION = 61; // ?
constexpr auto SCANCODE_RSHIFT = 62; // Right Shift
constexpr auto SCANCODE_LCTRL = 37; // Left Ctrl
constexpr auto SCANCODE_LWIN = 133; // Left Win
constexpr auto SCANCODE_LALT = 64; // Left Alt
constexpr auto SCANCODE_SPACE = 65; // Space
constexpr auto SCANCODE_RALT = 108; // Right Alt
constexpr auto SCANCODE_MENU = 135; // Right Menu button
constexpr auto SCANCODE_RWIN = 0; // Right Win
constexpr auto SCANCODE_RCTRL = 105; // Right Ctrl

constexpr auto SCANCODE_INSERT = 118;
constexpr auto SCANCODE_HOME = 110;
constexpr auto SCANCODE_PGUP = 112;
constexpr auto SCANCODE_DEL = 119;
constexpr auto SCANCODE_END = 115;
constexpr auto SCANCODE_PGDN = 117;

constexpr auto SCANCODE_UP = 111;
constexpr auto SCANCODE_LEFT = 113;
constexpr auto SCANCODE_DOWN = 116;
constexpr auto SCANCODE_RIGHT = 114;

constexpr auto SCANCODE_NUMLOCK = 77;
constexpr auto SCANCODE_PADSLASH = 106; // Keypad /
constexpr auto SCANCODE_PADMUL = 63; // Keypad *
constexpr auto SCANCODE_PAD7 = 79; // Keypad 7
constexpr auto SCANCODE_PAD8 = 80; // Keypad 8
constexpr auto SCANCODE_PAD9 = 81; // Keypad 9
constexpr auto SCANCODE_PADMINUS = 82; // Keypad -
constexpr auto SCANCODE_PAD4 = 83; // Keypad 4
constexpr auto SCANCODE_PAD5 = 84; // Keypad 5
constexpr auto SCANCODE_PAD6 = 85; // Keypad 6
constexpr auto SCANCODE_PADPLUS = 86; // Keypad +
constexpr auto SCANCODE_PAD1 = 87; // Keypad 1
constexpr auto SCANCODE_PAD2 = 88; // Keypad 2
constexpr auto SCANCODE_PAD3 = 89; // Keypad 3
constexpr auto SCANCODE_PAD0 = 90; // Keypad 0
constexpr auto SCANCODE_PADCOMA = 91; // Keypad .
constexpr auto SCANCODE_PADENTER = 105; // Keypad Enter
